#!/bin/bash

echo "TFF Hardware Testing Demo"
echo "=========================="
echo ""
echo "This script demonstrates how to test the TFF implementation on actual hardware."
echo ""
echo "1. Connect RP2040 to UpBoard:"
echo "   UpBoard USB-A Port → USB-OTG Adapter → RP2040 USB-C (Device Port)"
echo "                                     ↓"
echo "                          RP2040 USB-A (Host Port) → USB Keyboard"
echo ""
echo "2. Deploy firmware:"
echo "   ./deploy_tff.sh /home/guettli/projects/tff/my-combos.yaml"
echo ""
echo "3. Test TFF mappings:"
echo "   - Press 'j' then 'f' within 100ms → Should output backspace"
echo "   - Press 'f' then 'j' within 100ms → Should output delete"
echo "   - Press 'semicolon' then 'a' within 100ms → Should output home"
echo "   - Press 'a' then 'semicolon' within 100ms → Should output end"
echo ""
echo "4. Send fake keyboard events from UpBoard (for testing without physical keyboard):"
echo "   This would simulate keyboard input to the RP2040 USB-A host port."
echo ""
echo "The system is ready for hardware testing when the RP2040 is connected!"