#include "tff_wizard.h"
#include "tff_engine.h"
#include "tff_parser.h"
#include <algorithm>
#include <cctype>
#include <filesystem>
#include <fstream>
#include <sstream>

namespace tff {
namespace wizard {

namespace {

std::string trim(const std::string& s) {
    auto start = s.find_first_not_of(" \t\r\n");
    if (start == std::string::npos)
        return "";
    auto end = s.find_last_not_of(" \t\r\n");
    return s.substr(start, end - start + 1);
}

std::string toLower(const std::string& s) {
    std::string res = s;
    std::transform(res.begin(), res.end(), res.begin(),
                   [](unsigned char c) { return std::tolower(c); });
    return res;
}

bool askYesNo(std::istream& in, std::ostream& out, const std::string& prompt, bool default_val) {
    out << prompt << (default_val ? " [Y/n]: " : " [y/N]: ");
    std::string line;
    if (!std::getline(in, line)) {
        return default_val;
    }
    std::string trimmed = toLower(trim(line));
    if (trimmed.empty()) {
        return default_val;
    }
    if (trimmed == "y" || trimmed == "yes" || trimmed == "1" || trimmed == "true") {
        return true;
    }
    if (trimmed == "n" || trimmed == "no" || trimmed == "0" || trimmed == "false") {
        return false;
    }
    return default_val;
}

const std::vector<WizardPreset> PRESET_DEFINITIONS = {
    {"minimal", "Essential home-row delete, backspace, and escape chords with dual-role CapsLock",
     R"(# Ten Flying Fingers (TFF) - Minimal Configuration
# Fast home-row index finger chords and dual-role CapsLock
settings:
  combo_timeout_ms: 40
  tap_hold_timeout_ms: 200

combos:
  - keys: j f
    outKeys: backspace
  - keys: f j
    outKeys: delete
  - keys: d f j
    outKeys: esc

tap_hold:
  caps_lock: [esc, super, 200]
)"},
    {"vim-nav", "Vim-style H/J/K/L arrow navigation on Space-hold with index chords",
     R"(# Ten Flying Fingers (TFF) - Vim Navigation Preset
# Hold Space to activate modal navigation layer (H/J/K/L, Home, End, PgUp, PgDn)
settings:
  combo_timeout_ms: 40
  tap_hold_timeout_ms: 200

combos:
  - keys: j f
    outKeys: backspace
  - keys: f j
    outKeys: delete

tap_hold:
  caps_lock: [esc, super, 200]
  space: [space, nav, 200]

layers:
  nav:
    h: left
    j: down
    k: up
    l: right
    0: home
    4: end
    u: page_up
    d: page_down
    b: ctrl+left
    w: ctrl+right
    x: delete
)"},
    {"home-row-mods", "Home-row modifiers (A/S/D/F = Gui/Alt/Ctrl/Shift on hold)",
     R"(# Ten Flying Fingers (TFF) - Home-Row Modifiers Preset
# Dual-role home-row keys: tap for standard letter, hold for modifier
settings:
  combo_timeout_ms: 40
  tap_hold_timeout_ms: 180

tap_hold:
  # Left Hand (GACS layout: Gui, Alt, Ctrl, Shift)
  a: [a, super, 180]
  s: [s, alt, 180]
  d: [d, ctrl, 180]
  f: [f, shift, 180]

  # Right Hand (Shift, Ctrl, Alt, Gui)
  j: [j, shift, 180]
  k: [k, ctrl, 180]
  l: [l, alt, 180]
  semicolon: [semicolon, super, 180]
)"},
    {"full", "Comprehensive setup: combos, Space-Nav layer, dual-role CapsLock, and Auto-Shift",
     R"(# Ten Flying Fingers (TFF) - Full Power-User Preset
# Home-row chords, Space-Nav layer, dual-role keys, and Auto-Shift capitalization
settings:
  combo_timeout_ms: 40
  tap_hold_timeout_ms: 200

combos:
  - keys: j f
    outKeys: backspace
  - keys: f j
    outKeys: delete
  - keys: d f j
    outKeys: esc

tap_hold:
  caps_lock: [esc, super, 200]
  space: [space, nav, 200]

layers:
  nav:
    h: left
    j: down
    k: up
    l: right
    0: home
    4: end
    u: page_up
    d: page_down
    b: ctrl+left
    w: ctrl+right
    x: delete

auto_shift:
  enabled: true
  timeout_ms: 175
  keys: letters
)"}};

}  // namespace

const std::vector<WizardPreset>& getPresets() {
    return PRESET_DEFINITIONS;
}

const WizardPreset* findPreset(const std::string& name) {
    std::string lower = toLower(name);
    for (const auto& p : PRESET_DEFINITIONS) {
        if (toLower(p.name) == lower) {
            return &p;
        }
    }
    // Aliases
    if (lower == "vim" || lower == "nav")
        return findPreset("vim-nav");
    if (lower == "hrm" || lower == "mods" || lower == "homerow")
        return findPreset("home-row-mods");
    if (lower == "min" || lower == "default")
        return findPreset("minimal");
    if (lower == "all" || lower == "power" || lower == "power-user")
        return findPreset("full");

    return nullptr;
}

std::string generateConfigFromAnswers(const WizardAnswers& a) {
    std::ostringstream ss;
    ss << "# Ten Flying Fingers (TFF) Configuration\n"
       << "# Generated by 'tff init' configuration wizard\n"
       << "# Documentation: https://github.com/guettli/tff2\n\n";

    ss << "settings:\n"
       << "  combo_timeout_ms: " << a.combo_timeout_ms << "\n"
       << "  tap_hold_timeout_ms: " << a.tap_hold_timeout_ms << "\n\n";

    if (a.enable_home_row_combos && !a.enable_home_row_mods) {
        ss << "combos:\n"
           << "  # Home-row index finger chords\n"
           << "  - keys: j f\n"
           << "    outKeys: backspace\n"
           << "  - keys: f j\n"
           << "    outKeys: delete\n"
           << "  - keys: d f j\n"
           << "    outKeys: esc\n\n";
    } else if (a.enable_home_row_combos && a.enable_home_row_mods) {
        ss << "# Note: Home-row index chords on J/F/D are omitted because Home-Row Modifiers\n"
           << "# are configured on the same keys (avoiding tap-hold and combo conflicts).\n\n";
    }

    if (a.enable_caps_lock_dual_role || a.enable_space_nav_layer || a.enable_home_row_mods) {
        ss << "tap_hold:\n";
        if (a.enable_caps_lock_dual_role) {
            ss << "  # Caps Lock: tap for Escape, hold for Super/Win\n"
               << "  caps_lock: [esc, super, " << a.tap_hold_timeout_ms << "]\n";
        }
        if (a.enable_space_nav_layer) {
            ss << "  # Space: tap for Space, hold to activate Navigation layer\n"
               << "  space: [space, nav, " << a.tap_hold_timeout_ms << "]\n";
        }
        if (a.enable_home_row_mods) {
            ss << "  # Home-Row Modifiers\n"
               << "  a: [a, super, " << a.tap_hold_timeout_ms << "]\n"
               << "  s: [s, alt, " << a.tap_hold_timeout_ms << "]\n"
               << "  d: [d, ctrl, " << a.tap_hold_timeout_ms << "]\n"
               << "  f: [f, shift, " << a.tap_hold_timeout_ms << "]\n"
               << "  j: [j, shift, " << a.tap_hold_timeout_ms << "]\n"
               << "  k: [k, ctrl, " << a.tap_hold_timeout_ms << "]\n"
               << "  l: [l, alt, " << a.tap_hold_timeout_ms << "]\n"
               << "  semicolon: [semicolon, super, " << a.tap_hold_timeout_ms << "]\n";
        }
        ss << "\n";
    }

    if (a.enable_space_nav_layer) {
        ss << "layers:\n"
           << "  nav:\n"
           << "    h: left\n"
           << "    j: down\n"
           << "    k: up\n"
           << "    l: right\n"
           << "    0: home\n"
           << "    4: end\n"
           << "    u: page_up\n"
           << "    d: page_down\n"
           << "    b: ctrl+left\n"
           << "    w: ctrl+right\n"
           << "    x: delete\n\n";
    }

    if (a.enable_auto_shift) {
        ss << "auto_shift:\n"
           << "  enabled: true\n"
           << "  timeout_ms: 175\n"
           << "  keys: letters\n\n";
    }

    if (a.enable_leader_sequences) {
        ss << "leader:\n"
           << "  key: right_alt\n"
           << "  timeout_ms: 800\n"
           << "  sequences:\n"
           << "    w q: \":wq\"\n"
           << "    g s: \"git status\"\n";
    }

    return ss.str();
}

std::string getDefaultOutputPath() {
    const char* xdg_config = std::getenv("XDG_CONFIG_HOME");
    if (xdg_config != nullptr && xdg_config[0] != '\0') {
        return std::string(xdg_config) + "/tff/tff-combos.yaml";
    }

    const char* home = std::getenv("HOME");
    if (home != nullptr && home[0] != '\0') {
        return std::string(home) + "/.config/tff/tff-combos.yaml";
    }

    return "tff-combos.yaml";
}

int runWizard(const WizardOptions& options, std::istream& in, std::ostream& out) {
    if (options.list_presets) {
        out << "Available TFF Configuration Presets:\n\n";
        for (const auto& p : getPresets()) {
            out << "  " << p.name << "\n";
            out << "    " << p.description << "\n\n";
        }
        return 0;
    }

    std::string yaml_content;

    if (!options.preset_name.empty()) {
        const auto* preset = findPreset(options.preset_name);
        if (!preset) {
            out << "Error: Unknown preset '" << options.preset_name << "'.\n";
            out << "Use 'tff init --list-presets' to view available presets.\n";
            return 1;
        }
        yaml_content = preset->yaml_content;
        if (!options.print_only) {
            out << "Selected preset: " << preset->name << " (" << preset->description << ")\n";
        }
    } else if (options.non_interactive) {
        // Default non-interactive preset
        const auto* preset = findPreset("minimal");
        yaml_content = preset->yaml_content;
    } else {
        // Interactive mode
        out << "=======================================================\n";
        out << "       Ten Flying Fingers (TFF) Setup Wizard           \n";
        out << "=======================================================\n\n";
        out << "Choose a configuration starting point:\n";
        out << "  [1] Interactive interview (recommended custom setup)\n";
        out << "  [2] Preset: Minimal (fast home-row delete, backspace, esc)\n";
        out << "  [3] Preset: Vim Navigation (space-hold arrow navigation)\n";
        out << "  [4] Preset: Home-Row Modifiers (A/S/D/F = Gui/Alt/Ctrl/Shift)\n";
        out << "  [5] Preset: Full Power-User (Nav, Combos, Auto-Shift)\n\n";
        out << "Select an option [1-5, default: 1]: ";

        std::string choice_str;
        std::getline(in, choice_str);
        std::string choice = trim(choice_str);

        if (choice == "2") {
            yaml_content = findPreset("minimal")->yaml_content;
        } else if (choice == "3") {
            yaml_content = findPreset("vim-nav")->yaml_content;
        } else if (choice == "4") {
            yaml_content = findPreset("home-row-mods")->yaml_content;
        } else if (choice == "5") {
            yaml_content = findPreset("full")->yaml_content;
        } else {
            // Interactive interview
            WizardAnswers answers;
            out << "\n--- Custom Configuration Interview ---\n\n";

            answers.enable_home_row_combos = askYesNo(
                in, out,
                "1. Enable home-row chords (J+F -> Backspace, F+J -> Delete, D+F+J -> Escape)?",
                true);

            answers.enable_caps_lock_dual_role = askYesNo(
                in, out, "2. Enable dual-role Caps Lock (tap -> Escape, hold -> Super / Win key)?",
                true);

            answers.enable_space_nav_layer = askYesNo(
                in, out, "3. Enable Space-Nav layer (hold Space for H/J/K/L arrow navigation)?",
                true);

            answers.enable_home_row_mods = askYesNo(
                in, out,
                "4. Enable Home-Row Modifiers (A/S/D/F & J/K/L/; as Super/Alt/Ctrl/Shift on "
                "hold)?\n"
                "   (Note: Disables J/F/D home-row combos to prevent tap-hold modifier conflicts)",
                false);

            answers.enable_auto_shift = askYesNo(
                in, out, "5. Enable Auto-Shift (tap for lowercase, long-press for uppercase)?",
                false);

            answers.enable_leader_sequences = askYesNo(
                in, out, "6. Enable Vim-style Leader sequences (tap Leader followed by shortcut)?",
                false);

            yaml_content = generateConfigFromAnswers(answers);
        }
    }

    // Validate generated YAML configuration
    tff::Config cfg;
    std::string err;
    if (!tff::loadYamlConfig(yaml_content, cfg, err)) {
        out << "Internal Error: Generated configuration failed validation: " << err << "\n";
        return 1;
    }

    if (options.print_only) {
        out << yaml_content;
        return 0;
    }

    std::string target_path = options.output_path;
    if (target_path.empty()) {
        target_path = getDefaultOutputPath();
    }

    // Check if target file already exists
    std::error_code ec;
    bool file_exists = std::filesystem::exists(target_path, ec);

    if (file_exists && !options.force && !options.non_interactive) {
        out << "\nTarget configuration file already exists: " << target_path << "\n";
        bool overwrite = askYesNo(in, out, "Create backup and overwrite existing file?", false);
        if (!overwrite) {
            out << "Setup cancelled by user. Existing configuration was not modified.\n";
            return 0;
        }
    }

    // Create parent directory if needed
    std::filesystem::path p(target_path);
    if (p.has_parent_path()) {
        std::filesystem::create_directories(p.parent_path(), ec);
    }

    // Create backup if file exists
    if (file_exists) {
        std::string backup_path = target_path + ".bak";
        std::filesystem::copy_file(target_path, backup_path,
                                   std::filesystem::copy_options::overwrite_existing, ec);
        if (ec) {
            out << "Error: Failed to create backup file " << backup_path << ": " << ec.message()
                << "\n";
            return 1;
        }
        out << "Created backup: " << backup_path << "\n";
    }

    // Write file
    std::ofstream out_file(target_path);
    if (!out_file.is_open()) {
        out << "Error: Could not open file for writing: " << target_path << "\n";
        return 1;
    }
    out_file << yaml_content;
    out_file.close();

    out << "\n✓ Successfully saved configuration to " << target_path << "\n";
    out << "  Active features: " << cfg.combos.size() << " combo(s), " << cfg.tap_hold_keys.size()
        << " tap-hold key(s), " << cfg.layers.size() << " layer(s)";
    if (cfg.auto_shift.enabled) {
        out << ", auto-shift enabled";
    }
    out << "\n\nNext steps:\n";
    out << "  1. Test your configuration:   tff validate " << target_path << "\n";
    out << "  2. View your visual cheatsheet: tff cheatsheet " << target_path << "\n";
    out << "  3. Start the remapper daemon:   tff --config " << target_path << "\n";

    return 0;
}

}  // namespace wizard
}  // namespace tff
